Move movement

# if nothing is specified here, we'll fall back to the default values from the
# param server. Otherwise, though, we'll use the value here (either in meters
# or radians)
std_msgs/Float32 custom_distance
---
std_msgs/Bool state
