fixed_frame: "world"
base_frame: "base_link"
use_imu: false
use_odom: true
use_vel: true

movement_utils:
    linear_travel_per_step   : 0.25
    linear_travel_threshold  : 0.01
    linear_vel               : 0.2
    angular_travel_per_step  : 20
    angular_travel_threshold : 2
    angular_vel              : 0.35
    scaling_factor           : 1
    use_pose2d               : true

rplidarNode:
    serial_port: "/dev/ttyUSB1"

